-- A one-time code sent to a customer's phone, for storefront sign-in.
--
-- Hand-written rather than generated by `migrate dev`: this database's user
-- cannot create the shadow database that command needs (P3014). The SQL below
-- is `prisma migrate diff --from-config-datasource --to-schema` verbatim, so it
-- is the same statement `migrate dev` would have produced.
--
-- The code is stored hashed with a per-row salt. A live one-time code is a
-- credential for the few minutes it exists, and a dump that hands over every
-- customer's in-flight sign-in code is the same class of incident as leaking
-- passwords, only shorter-lived.
--
-- Collation stated explicitly: MySQL 8 defaults new tables to
-- utf8mb4_0900_ai_ci, and every other table in this schema is unicode_ci.

CREATE TABLE `CustomerOtp` (
    `id` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(20) NOT NULL,
    `codeHash` VARCHAR(64) NOT NULL,
    `salt` VARCHAR(32) NOT NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `attempts` INTEGER NOT NULL DEFAULT 0,
    `consumedAt` DATETIME(3) NULL,
    `ip` VARCHAR(45) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `CustomerOtp_phone_createdAt_idx`(`phone`, `createdAt`),
    INDEX `CustomerOtp_expiresAt_idx`(`expiresAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
