import { test } from 'node:test';
import assert from 'node:assert/strict';
import { gstinCheckDigit, isValidGstin, normalizeGstin, GSTIN_PATTERN } from './gstin.ts';

const CHARSET = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';

/**
 * The published algorithm, written the other way round.
 *
 * The canonical implementation walks the 14 characters from the **right** with
 * the weight starting at 2; `gstinCheckDigit` walks from the left with it
 * starting at 1. Those are the same weighting, and this file exists to prove
 * it rather than assume it — a test that only asked whether the implementation
 * agreed with itself would pass just as happily with the weights reversed.
 */
function referenceCheckDigit(first14: string): string {
  let factor = 2;
  let sum = 0;
  for (let i = first14.length - 1; i >= 0; i -= 1) {
    const codePoint = CHARSET.indexOf(first14[i]!);
    const product = factor * codePoint;
    factor = factor === 2 ? 1 : 2;
    sum += Math.floor(product / 36) + (product % 36);
  }
  return CHARSET[(36 - (sum % 36)) % 36]!;
}

/** A shape-valid 14-character prefix, with the check digit left off. */
function prefix(state: string, pan: string, entity: string): string {
  return `${state}${pan}${entity}Z`;
}

/** …and the same, completed. Built, never recalled: see the note below. */
function build(state: string, pan: string, entity: string): string {
  const head = prefix(state, pan, entity);
  return head + gstinCheckDigit(head);
}

/*
 * Fixtures are **constructed**, not quoted.
 *
 * The first draft of this file used GSTINs of real companies written from
 * memory. Two of six happened to satisfy the checksum, which looked like
 * partial success and was in fact luck — the numbers were wrong. A recalled
 * 15-character string is not a fixture; it is a guess that costs an afternoon
 * when it disagrees with correct code. So the valid cases here are generated by
 * the algorithm, and the algorithm is checked against an independent
 * implementation of the published one above.
 */

test('the check digit agrees with the published algorithm, walked the other way', () => {
  // Exhaustive over a spread of prefixes rather than one lucky example.
  const states = ['01', '07', '23', '27', '29', '33', '36'];
  const pans = ['AAACR', 'AAPFU', 'ZZZZZ', 'ABCDE'];
  const serials = ['0000', '5055', '9999', '1234'];
  const checks = ['A', 'M', 'Z'];
  const entities = ['1', '9', 'A', 'Z'];

  let cases = 0;
  for (const state of states) {
    for (const pan of pans) {
      for (const serial of serials) {
        for (const check of checks) {
          for (const entity of entities) {
            const head = prefix(state, `${pan}${serial}${check}`, entity);
            assert.equal(gstinCheckDigit(head), referenceCheckDigit(head), head);
            cases += 1;
          }
        }
      }
    }
  }
  assert.ok(cases > 1000, `expected a real spread, got ${cases}`);
});

test('a constructed GSTIN passes both the pattern and the checksum', () => {
  const gstin = build('23', 'AABCU9603R', '1');
  assert.equal(gstin.length, 15);
  assert.ok(GSTIN_PATTERN.test(gstin));
  assert.equal(isValidGstin(gstin), true);
});

test('case and stray spaces are the customer being human, not an error', () => {
  const gstin = build('27', 'AAACR5055K', '1');
  assert.equal(normalizeGstin(`  ${gstin.toLowerCase()} `), gstin);
  assert.equal(isValidGstin(gstin.toLowerCase()), true);
  assert.equal(isValidGstin(` ${gstin} `), true);
  // Pasted out of an email, split across the PAN boundary.
  assert.equal(isValidGstin(`${gstin.slice(0, 7)} ${gstin.slice(7)}`), true);
});

test('the checksum catches a transposition the pattern cannot', () => {
  const gstin = build('27', 'AAACR5055K', '1');
  // Swap the two digits inside the serial: still 15 characters, still exactly
  // the right shape, still passes the regex — and is nobody's GSTIN.
  const transposed = `${gstin.slice(0, 8)}${gstin[9]}${gstin[8]}${gstin.slice(10)}`;
  assert.notEqual(transposed, gstin, 'the fixture must actually differ');
  assert.ok(GSTIN_PATTERN.test(transposed), 'the shape is intact, which is the point');
  assert.equal(isValidGstin(transposed), false);
});

test('every single-character corruption is caught', () => {
  const gstin = build('23', 'AABCU9603R', '1');

  let checked = 0;
  for (let i = 0; i < 14; i += 1) {
    // Substitute a character of the same class, so the pattern still passes and
    // only the checksum can object.
    const original = gstin[i]!;
    const pool = /\d/.test(original) ? '0123456789' : 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    for (const replacement of pool) {
      if (replacement === original) continue;
      const corrupted = gstin.slice(0, i) + replacement + gstin.slice(i + 1);
      if (!GSTIN_PATTERN.test(corrupted)) continue;
      assert.equal(isValidGstin(corrupted), false, `${corrupted} should fail`);
      checked += 1;
    }
  }
  assert.ok(checked > 100, `expected many corruptions, checked ${checked}`);
});

test('a wrong check digit is refused', () => {
  const gstin = build('27', 'AAACR5055K', '1');
  for (const wrong of CHARSET) {
    if (wrong === gstin[14]) continue;
    assert.equal(isValidGstin(gstin.slice(0, 14) + wrong), false);
  }
});

test('malformed input is refused rather than half-read', () => {
  const gstin = build('27', 'AAACR5055K', '1');

  assert.equal(isValidGstin(''), false);
  assert.equal(isValidGstin(gstin.slice(0, 14)), false, '14 characters');
  assert.equal(isValidGstin(`${gstin}5`), false, '16 characters');
  assert.equal(isValidGstin(gstin.slice(2)), false, 'no state digits');
  // The 14th character is always a literal Z.
  assert.equal(isValidGstin(`${gstin.slice(0, 13)}Y${gstin[14]}`), false);
  // The entity character cannot be 0.
  assert.equal(isValidGstin(`${gstin.slice(0, 12)}0${gstin.slice(13)}`), false);
  // A PAN block of digits rather than letters.
  assert.equal(isValidGstin('2712345 5055K1Z5'), false);
});

test('a check digit is refused for input that is not 14 valid characters', () => {
  assert.equal(gstinCheckDigit(''), null);
  assert.equal(gstinCheckDigit(build('27', 'AAACR5055K', '1')), null, '15 is too many');
  // A character outside the base-36 alphabet has no value to weigh.
  assert.equal(gstinCheckDigit('27AAACR5055K1-'), null);
});
